name: Run Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Run Maven tests
      run: mvn test